version: '3'
services:
  database:
    build:
      context: ./database
    container_name: database_tracker
    image: database_tracker
    networks:
      - tracker_network
  discovery:
    build:
      context: ./discovery
    container_name: discovery_tracker
    image: discovery_tracker
    networks:
      - tracker_network
    ports:
      - 8761:8761
  gateway:
    build:
      context: ./gateway
    container_name: gateway_tracker
    image: gateway_tracker
    networks:
      - tracker_network
    ports:
      - 8888:8888
    environment:
      - TRACKER_JWT_EXPIRATION=86400
      - TRACKER_JWT_HEADER=Authorization
      - TRACKER_JWT_PREFIX=Bearer
      - TRACKER_JWT_LOGIN_URL=/login
      - TRACKER_JWT_SECRET=tetetsdpkmfe343KFMWKEF
  authcenter:
    build:
      context: ./authcenter
    container_name: authcenter
    image: authcenter
    networks:
      - tracker_network
    environment:
      - TRACKER_JWT_EXPIRATION=86400
      - TRACKER_JWT_HEADER=Authorization
      - TRACKER_JWT_PREFIX=Bearer
      - TRACKER_JWT_LOGIN_URL=/login
      - TRACKER_JWT_SECRET=tetetsdpkmfe343KFMWKEF
  core:
    build:
      context: .
    container_name: core_tracker
    image: core_tracker
    environment:
      - FILE_SYSTEM_PROVIDER=HOST
      - ROOT_DIR=/
      - TRACKER_DRIVER_CLASS_NAME=org.postgresql.Driver
      - TRACKER_DB_URL=jdbc:postgresql://database:5432/tracker_db
      - TRACKER_DB_USER=postgres
      - TRACKER_DB_PASSWORD=postgres
      - TRACKER_DB_MAXIMUM_POOL_SIZE=5
      - TRACKER_INFO_URL=http://info_tracker:9016/
    networks:
      - tracker_network
  report:
    build:
      context: ./report
    container_name: report_tracker
    image: report_tracker
    environment:
      - TRACKER_DRIVER_CLASS_NAME=org.postgresql.Driver
      - TRACKER_DB_URL=jdbc:postgresql://database:5432/tracker_db
      - TRACKER_DB_USER=postgres
      - TRACKER_DB_PASSWORD=postgres
      - TRACKER_DB_MAXIMUM_POOL_SIZE=5
    networks:
      - tracker_network
  info:
    build:
      context: ./info
    container_name: info_tracker
    image: info_tracker
    ports:
      - 9016:9016

networks:
  tracker_network:
    driver: bridge