eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
spring:
  application:
    name: gateway
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    auth-center:
      path: /login/**
      serviceId: authcenter
      sensitiveHeaders: Cookie, Set-Cookie
      stripPrefix: false
    core:
      path: /core/**
      serviceId: core
      stripPrefix: false
      sensitiveHeaders:
    report:
      path: /report/**
      serviceId: report
      stripPrefix: false
      sensitiveHeaders:

server:
  port: 8888