eureka:
  client:
    instance:
      prefer-ip-address: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
spring:
  application:
    name: gateway
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    core:
      path: /core/**
      serviceId: core
    report:
      path: /report/**
      serviceId: report

server:
  port: 8888