eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

server:
  port: 8888